[package]
name = "tokio-postgres-rustls"
description = "Rustls integration for tokio-postgres"
version = "0.11.1"
authors = ["Jasper Hugo <jasper@jasperhugo.com>"]
repository = "https://github.com/jbg/tokio-postgres-rustls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
ring = { version = "0.17", default-features = false }
rustls = { version = "0.22.1", default-features = false }
tokio = { version = "1", default-features = false }
tokio-postgres = { git = "https://github.com/neondatabase/rust-postgres", branch="neon" }
tokio-rustls = { version = "0.25", default-features = false }
x509-certificate = {version = "0.23", default-features = false }

[dev-dependencies]
env_logger = { version = "0.10", default-features = false }
tokio = { version = "1", features = ["macros", "rt"] }
tokio-postgres = { git = "https://github.com/neondatabase/rust-postgres", branch="neon" }
rustls = { version = "0.22" }
